export const SET_MOVIE = 'SET_MOVIE';

export const SET_REVIEW_ID = 'SET_REVIEW_ID';

export const SET_DISCUSSION_TYPE = 'SET_DISCUSSION_TYPE'; //  设置当前评论的类别

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_FAVORITE_COMMENTS = 'SET_FAVORITE_COMMENTS';

export const SET_WATCHED_MOVIES = 'SET_WATCHED_MOVIES';

export const SET_WANTED_MOVIES = 'SET_WANTED_MOVIES';

export const SET_COLLECT_CELEBRITY = 'SET_COLLECT_CELEBRITY';

export const SET_CELEBRITY_ID = 'SET_CELEBRITY_ID';
